replicaCount: 2

image:
  repository: your-registry/kafka-api-consumer
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 2112

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
